version: '2'
services:
  influxdb:
    image: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  redis:
    image: redis
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana
    links:
      - "influxdb:influxdb"
    ports:
      - "3000:3000"
  cron:
    build: .
    links:
      - "influxdb:influxdb"
      - "redis:redis"

volumes:
  influxdb-data:

